import { defineConfig } from 'astro/config';
import { readFileSync } from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'url';
import remarkWikilinks from './src/plugins/remark-wikilinks.mjs';

const __dirname = fileURLToPath(new URL('.', import.meta.url));

let noteMap = new Map();
let catMap = new Map();

try {
  const raw = readFileSync(join(__dirname, 'slug-map.json'), 'utf-8'); // generated by copy-vault.js
  const data = JSON.parse(raw);
  noteMap = new Map(
    Object.entries(data.notes).map(([k, v]) => [k, `/chads-human-guide/notes/${v}`])
  );
  catMap = new Map(
    Object.entries(data.categories).map(([k, v]) => [k, `/chads-human-guide/category/${v}`])
  );
} catch {
  // slug-map.json doesn't exist yet — run: npm run copy-vault
}

export default defineConfig({
  site: 'https://charliemonaghan.github.io',
  base: '/chads-human-guide',
  output: 'static',
  markdown: {
    remarkPlugins: [[remarkWikilinks, { noteMap, catMap }]],
  },
});
